#!/usr/bin/env python2.7
# -*- coding: utf-8 -*-
##############################################################################
# (c) The copyright relating to this work is owned jointly by the Crown,
# Met Office and NERC 2014. However, it has been created with the help of the
# GungHo Consortium, whose members are identified at
# https://puma.nerc.ac.uk/trac/GungHo/wiki
##############################################################################
'''
Wraps the cubedsphere mesh generator so it may be controlled using command line
arguments.
'''

from __future__ import print_function;

import argparse
import os
import os.path
import subprocess
import sys
import tempfile

if __name__ == '__main__':
  parser = argparse.ArgumentParser( add_help=False, \
                  description='Generate a cubedsphere mesh in UGRID format.' )
  parser.add_argument( '-help', '-h', '--help', action='help', \
                       help='Display this message' )
  parser.add_argument( 'ndiv', help='Elements on a panel side' )
  parser.add_argument( 'filename', help='Mesh file to create' )
  arguments = parser.parse_args()

  namelist = '''
&cubedsphere_mesh_generator
  edge_cells = {ndiv}
  mesh_filename = {filename}
/
             '''.strip()

  handle, tempname = tempfile.mkstemp( suffix='.nml', text=True )
  try:
    with os.fdopen( handle, 'w' ) as temporaryFile:
      print( namelist.format( ndiv=arguments.ndiv, \
                              filename=arguments.filename ) + '\n', \
             file=temporaryFile )

    command = [os.path.join( os.path.dirname(sys.argv[0]), \
                             'cubedsphere_mesh_generator' ), tempname]
    subprocess.check_call( command )
  except Exception:
    exception, value, traceback = sys.exc_info()
    os.remove( tempname )
    raise value, None, traceback
