# This input file can be generated by running the:
# lfric_atm nightly test suite
# It is generated by the nwp_gal9_ls_and_jedi test
INPUT=ls_and_jedi_trajectory_2018041421-2018041504.nc
OUTPUT=final_ls.nc

TIMESTEP=$(ncks -d time,0 -v time ${INPUT} | grep "time =" | sed -e "s/.*= //;s/ .*//"  | tr -d -c 0-9)

# Change the file from a time sequence of 3d fields(axes=space),
# to a single 4d field (axes=space+time) by changing the time dimension
# from unlimited to time=NN.
echo Making time the record dimension
ncks --fix_rec_dmn time -O $INPUT ${INPUT}_tmp

# Drop fields needed by JEDI but not linear
ncks -O -C -q -v Mesh2d,Mesh2d_node_x,Mesh2d_node_y,Mesh2d_edge_x,Mesh2d_edge_y,Mesh2d_edge_nodes,Mesh2d_face_x,Mesh2d_face_y,Mesh2d_face_nodes,Mesh2d_face_edges,Mesh2d_edge_face_links,Mesh2d_face_links,full_levels,half_levels,time,time_bounds,exner,rho,theta,m_v,m_cl,m_ci,m_r ${INPUT}_tmp ${INPUT}_tmp

echo Shifting time back by ${TIMESTEP}
# Change the file so that the time starts at 0
ncap2 -O -s time-=${TIMESTEP} ${INPUT}_tmp ${INPUT}_tmp
ncap2 -O -s time_bounds-=${TIMESTEP} ${INPUT}_tmp ${OUTPUT}
rm *tmp*
echo Output ${OUTPUT}
